Корректировки запуска setup скрипта, скрипта хука и зависимость в composer.json

diff --git a/src/pre-commit b/src/pre-commit
--- a/src/pre-commit
+++ b/src/pre-commit
@@ -6,35 +6,38 @@ STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \
 # Determine if a file list is passed
 if [ "$#" -eq 1 ]
 then
-	oIFS=$IFS
-	IFS='
-	'
-	SFILES="$1"
-	IFS=$oIFS
+    oIFS=$IFS
+    IFS='
+    '
+    SFILES="$1"
+    IFS=$oIFS
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
 echo "Checking PHP Lint..."
 for FILE in $SFILES
 do
-	php -l -d display_errors=0 $PROJECT/$FILE
-	if [ $? != 0 ]
-	then
-		echo "Fix the error before commit."
-		exit 1
-	fi
-	FILES="$FILES $PROJECT/$FILE"
+    php -l -d display_errors=0 $PROJECT/$FILE
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
+    fi
+    FILES="$FILES $PROJECT/$FILE"
 done
 
 if [ "$FILES" != "" ]
 then
-	echo "Running Code Sniffer..."
-	./vendor/bin/phpcs --standard=phpcs.xml --encoding=utf-8 -n -p $FILES
-	if [ $? != 0 ]
-	then
-		echo "Fix the error before commit!"
-		exit 1
-	fi
+    echo "Running Code Sniffer. Code standard PSR2."
+    ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -n -p $FILES
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit!"
+        echo "Run"
+        echo "  ./vendor/bin/phpcbf $FILES"
+        echo "for automatic fix."
+        exit 1
+    fi
 fi
 
 exit $?
